# Generated by Django 3.1.1 on 2020-09-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ticker', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
