# Generated by Django 3.1.1 on 2020-09-21 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investinfo', '0004_auto_20200919_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticker',
            name='id',
        ),
        migrations.AddField(
            model_name='ticker',
            name='logo_url',
            field=models.CharField(default='https://logo.clearbit.com/', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticker',
            name='ticker',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
