# Generated by Django 3.1.1 on 2020-09-22 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('investinfo', '0006_auto_20200921_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('open', models.DecimalField(decimal_places=5, max_digits=11)),
                ('high', models.DecimalField(decimal_places=5, max_digits=11)),
                ('low', models.DecimalField(decimal_places=5, max_digits=11)),
                ('close', models.DecimalField(decimal_places=5, max_digits=11)),
                ('adj_close', models.DecimalField(decimal_places=5, max_digits=11)),
                ('volume', models.IntegerField()),
                ('ticker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investinfo.ticker')),
            ],
        ),
    ]
