# Generated by Django 3.1.1 on 2020-09-22 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investinfo', '0007_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='date',
            new_name='Datetime',
        ),
    ]
