# Generated by Django 3.1.1 on 2020-11-01 19:27

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('investinfo', '0009_auto_20200922_1220'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='ticker',
            managers=[
                ('available', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='ticker',
            old_name='description',
            new_name='longBusinessSummary',
        ),
        migrations.RenameField(
            model_name='ticker',
            old_name='name',
            new_name='longName',
        ),
        migrations.RenameField(
            model_name='ticker',
            old_name='ticker',
            new_name='symbol',
        ),
    ]
