# Generated by Django 3.1.1 on 2020-11-03 12:15

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('investinfo', '0010_auto_20201102_0027'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='data',
            managers=[
                ('get_data', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='data',
            constraint=models.UniqueConstraint(fields=('ticker_id', 'datetime'), name='unique data record'),
        ),
        migrations.AlterModelTable(
            name='data',
            table='investinfo_data',
        ),
    ]
